### ISSUE TITLE
The error message is too long when the command entered is wrong?

### ISSUE THREAD

**Issue by nyngwang** [VonHeikemen/fine-cmdline.nvim#19]
As title. As img:

<img src="https://user-images.githubusercontent.com/24765272/146818052-24de2f0b-fc81-45f3-a7b9-5a8205294792.png" width="800">

while normally the error is short:

<img src="https://user-images.githubusercontent.com/24765272/146817984-6663c0ff-42a3-4da6-a93b-3c92dc7a1af8.png" width="400">

**Comment by VonHeikemen** [comment]
Fair enough. This now fixed in [501e7a1](https://github.com/VonHeikemen/fine-cmdline.nvim/commit/501e7a17a2b6ac0c3c3ccc7d1c14a463cf8dc067).
