### ISSUE TITLE
Adding fn.complete_and_next_item

### ISSUE THREAD

**Issue by akai54** [VonHeikemen/fine-cmdline.nvim#22]
When you use the regular cmdline of nvim, when you press Tab it shows you the completion menu + selects the next item at the same time, While right now with the current Fine-CmdLine we have to press the Tab once to show the completion menu then we have to press it again to make it start selecting entries from the completion 

So I suggest a new function called fn.complete_and_next_item that would show the menu and directly choose the next item without having to press Tab again.

**Comment by VonHeikemen** [comment]
Behaviour on the menu depends on [completeopt](https://neovim.io/doc/user/options.html#'completeopt'). With `set completeopt=menu,menuone` it should do what you want.

**Comment by akai54** [comment]
> Or actually, just removing `noselect` from the list works fine.

Indeed that worked, thank you. This issue shall be closed now.
