### ISSUE TITLE
Visual mode support ?

### ISSUE THREAD

**Issue by akai54** [VonHeikemen/fine-cmdline.nvim#23]
Hey,
If I'm not mistaken there is no mention to visual mode here, yet it's important !.
When I tried to do a visual mode selection then invoke the plug-in I got this error message : 
E481: No range allowed.

**Comment by VonHeikemen** [comment]
I should probably document that. This should work fine.

```vim
:<C-u>FineCmdline '<,'><CR>
```

**Comment by akai54** [comment]
Indeed it worked !
Thank you, now I'm gonna close this issue.
