### ISSUE TITLE
Integration with wilder

### ISSUE THREAD

**Issue by luiz00martins** [VonHeikemen/fine-cmdline.nvim#24]
Looking for an integration for [wilder.nvim](https://github.com/gelguy/wilder.nvim), using it as a source for autocompletion.

I've also opened an [issue on wilder](https://github.com/gelguy/wilder.nvim/issues/144), to make sure that this is viable.

**Comment by VonHeikemen** [comment]
They have  a [Command palette](https://github.com/gelguy/wilder.nvim#command-palette-experimental) feature. It's experimental but it basically makes the integration unnecesary.
