### ISSUE TITLE
[Feature] Integrate vim.ui_attach

### ISSUE THREAD

**Issue by akinsho** [VonHeikemen/fine-cmdline.nvim#26]
Hi @VonHeikemen 👋🏿 

I came across this plugin a little while ago, but was waiting to see if externalizing the commandline would become possible in neovim via lua. Thankfully a PR was just merged to allow this in nightly https://github.com/neovim/neovim/pull/16396, i.e. a user/plugin can now do something like
```lua
vim.ui_attach(namespace_id, { ext_cmdline = true }, function(event, ...)
  if event === "cmdline_show" then
    -- args => content, pos, first_char, prompt, indent, level
    open_fine_cmdline_window(first_char .. prompt .. content[1][2])
  end
end)
```

It seems (without looking at this plugin's codebase) that it has most of the pieces to handle externalizing the command line and the main thing that would need to change would be rather than collecting user input directly, you would be populating the contents of your popup with the `ui_attach` messages?

What do you think? Is this something that is interesting to you? Not sure if this was on your radar or not

I worked with this functionality [quite a while ago](https://github.com/onivim/oni/pull/1177/files) and for the most part all that needs to happen is the content needs to be dumped into a window, so it just behaves as a view, neovim will just handle the commandline behaviour itself.

**Comment by VonHeikemen** [comment]
Wait a minute... does this mean I can access `command-line-mode` inside the floating window?

**Comment by akinsho** [comment]
Not sure that I know what you mean re `command-line-mode`, but the window would essentially represent the command line completely, you would get events saying what should be happening in the command line and the window would just render the output. So if a user types `:help blah` it wouldn't open the command line, but instead you would receive a message in your callback which you would then render in the box, and so they would keep typing as normal, and you would just continue to dump the output. At some point they'd press enter or something, and I guess you'd get a message to hide the command line, and you'd close the popup

Re. the wildmenu you can also externalize this and so have another window which behaves like the wildmenu e.g. showing the history and completions etc.

**Comment by VonHeikemen** [comment]
It's a mode. It has separate keybindings, abbreviations, enables live previews in commands.

Other plugins can check if the user is in command-line-mode

```lua
if vim.api.nvim_get_mode().mode == 'c' then
  -- do this thing....
end
```

**Comment by akinsho** [comment]
Ah, lol sorry, I just thought you meant something fancier/different written out like that I thought it was some new plugin or something. Well AFAIK neovim will be in commandline mode when the ui events are coming through, so those plugins should still all trigger whatever they are supposed to. It's really just a change of the UI for the commandline. There will be some awkwardness with the wildmenu needing a UI as well otherwise it'll be confusing and things like wilder and cmp-cmdline will have to adapt

**Comment by folke** [comment]
@akinsho I just **silently** (for now) released a new plugin that does. See https://github.com/folke/noice.nvim

Feel free to test it out and give some feedback :)

**Comment by akinsho** [comment]
@folke that looks amazing, will be giving it a try ASAP 🏃🏾‍♂️🙌🏾

**Comment by akinsho** [comment]
Just tried it out, and it works really nicely 👍🏿 I'll close this out since I was just fishing to see if any plugin that already existed could be adapted to use this new functionality and yours ticks that box 👍🏿
