### ISSUE TITLE
Integration with wilder.nvim

### ISSUE THREAD

**Issue by domas-v** [VonHeikemen/fine-cmdline.nvim#4]
Hi there. Is there a possibility to integrate wilder.nvim suggestions/completion in the window?

**Comment by VonHeikemen** [comment]
I'm not familiar with wilder.nvim. My idea with this plugin is to make it possible through configuration. If it is possible I will add it to the readme, or a separate markdown file (maybe like a recipes.md).

I will take a look a wilder.nvim in another moment and go back to this issue.

**Comment by Shougo** [comment]
ddc.vim integration is already available.

https://github.com/Shougo/ddc.vim/issues/32#issuecomment-974608862

**Comment by yingzhu146** [comment]
See https://github.com/gelguy/wilder.nvim/issues/78

**Comment by VonHeikemen** [comment]
I still haven't check wilder.nvim, but I've added some changes that should make the integration easier.

If you could test this config.

```lua
local fineline = require('fine-cmdline')
local fn = fineline.fn

fineline.setup({
  cmdline = {
    enable_keymaps = false
  },
  hooks = {
    before_mount = function(input)
      -- Prompt can influence the completion engine.
      -- This is your chance to change it to something that works for you
      input.input_props.prompt = ': '
    end,
    set_keymaps = function(imap, feedkeys)
      -- Restore default keybindings...
      -- Except for `<Tab>`, that's what everyone uses to autocomplete
      imap('<Esc>', fn.close)
      imap('<C-c>', fn.close)

      imap('<Up>', fn.up_history)
      imap('<Down>', fn.down_history)
    end
  }
})
```

**Comment by VonHeikemen** [comment]
Integration with `wilder.nvim` is not going to  happen. They check specifically if the user is in `commandline-mode`, which can't be enabled by this plugin.

It is a bit of a shame, because their popup renderer would work just fine outside the built-in command-line.
