### ISSUE TITLE
Add option to disable `<Tab>` and `<S-Tab>` or  an option to disable all default bindings?

### ISSUE THREAD

**Issue by VonHeikemen** [VonHeikemen/fine-cmdline.nvim#5]
In theory, if I never remap `<Tab>` then integration with completion engines should be easier.

This integration should be possible through configuration in the `.setup()` function. Disabling all defaults should not be a big deal... it's just three more lines of code you'll have to copy/paste from the documentation.

**Comment by Shougo** [comment]
I think disable all default mappings is better.

**Comment by VonHeikemen** [comment]
Disable all mappings it is.

**Comment by Shougo** [comment]
It works!
