### ISSUE TITLE
Persistent list for previously ran commands and commands being entered.

### ISSUE THREAD

**Issue by zim0369** [VonHeikemen/fine-cmdline.nvim#6]
I wish that this plugins window was similar to `q:` where I can see the previously ran commands and use vim keybindings. It'd also be great to see command suggestions when typing commands without having to press tab to see a list.

**Comment by VonHeikemen** [comment]
> I wish that this plugins window was similar to q: where I can see the previously ran commands 

I can't do that. You might want to check out this: [cmdbuf.nvim](https://github.com/notomo/cmdbuf.nvim) or maybe [Telescope](https://github.com/nvim-telescope/telescope.nvim) (specifically `Telescope command_history`).

> and use vim keybindings

There is an issue with normal. I'm working on it.

>  It'd also be great to see command suggestions when typing commands without having to press tab to see a list.

For this you'll need full on completion engine.

**Comment by zim0369** [comment]
Okay
