### ISSUE TITLE
Disable signcolumns in cmdline

### ISSUE THREAD

**Issue by mystilleef** [VonHeikemen/fine-cmdline.nvim#9]
`fine-cmdline` shows sign columns. Is there a reason they're enabled? I've attached a screenshot below.

![finecmdlinebug](https://user-images.githubusercontent.com/273399/142731511-d5e3b4e2-1742-4e42-9321-055517a130f1.png)

**Comment by VonHeikemen** [comment]
Now that's odd.I don't enable them.

You should be able to turn them off, though.

```lua
require('fine-cmdline').setup({
  popup = {
    win_options = {
      signcolumn = 'no'
    }
  }
})
```

**Comment by mystilleef** [comment]
That worked, thanks.
